import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getIds } from '@/util/ids';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { traceId, spanId } = getIds();
  console.info(`[Log from layout.tsx]\ttraceId=${traceId}\tspanId=${spanId}`);
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
